//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PossibleAnswer
    {
        public long Id { get; set; }
        public string Text { get; set; }
        public bool IsRight { get; set; }
        public long QuestionId { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
